#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

export PATH=$HOME/bin:$PATH

# CDPATH allows us to use jhq and get quick cd for free
if [ -f /usr/bin/ghq ]; then
  export CDPATH=$HOME/src/github.com/juxt:$HOME/src/github.com
fi

export GEM_HOME=$(ruby -e 'print Gem.user_dir')

export PATH=$HOME/src/github.com/juxt/dotfiles/bin:$GEM_HOME/bin:$PATH
